version: '3.9'

services:
  db:
    image: postgres:16
    container_name: kgolf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: kgolf
      POSTGRES_PASSWORD: kgolf_password
      POSTGRES_DB: kgolf_app
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kgolf -d kgolf_app']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kgolf_net

networks:
  kgolf_net:
    driver: bridge

volumes:
  pg_data:
    driver: local
